### ISSUE TITLE
Package.json Dependency List

### ISSUE THREAD

**Issue by erayaydin** [huytd/node-online-game-template#1]
Package.json doesn't has dependency list.

``` json
"dependencies": {
    "express": "^4.13.0",
    "socket.io": "^1.3.5"
}
```

**Comment by keneo** [comment]
+1

```
C:\prj\github-downloads\node-online-game-template>npm install
npm WARN package.json your-game-name-here@1.0.0 No repository field.

C:\prj\github-downloads\node-online-game-template>npm start

> your-game-name-here@1.0.0 start C:\prj\github-downloads\node-online-game-templ
ate
> node server/server.js

module.js:338
    throw err;
          ^
Error: Cannot find module 'express'
    at Function.Module._resolveFilename (module.js:336:15)
    at Function.Module._load (module.js:278:25)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at Object.<anonymous> (C:\prj\github-downloads\node-online-game-template\ser
ver\server.js:1:77)
    at Module._compile (module.js:460:26)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Function.Module.runMain (module.js:501:10)

npm ERR! Windows_NT 6.1.7601
npm ERR! argv "C:\\Program Files\\nodejs\\\\node.exe" "C:\\Program Files\\nodejs
\\node_modules\\npm\\bin\\npm-cli.js" "start"
npm ERR! node v0.12.0
npm ERR! npm  v2.5.1
npm ERR! code ELIFECYCLE
npm ERR! your-game-name-here@1.0.0 start: `node server/server.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the your-game-name-here@1.0.0 start script 'node server/serve
r.js'.
npm ERR! This is most likely a problem with the your-game-name-here package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node server/server.js
npm ERR! You can get their info via:
npm ERR!     npm owner ls your-game-name-here
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     C:\prj\github-downloads\node-online-game-template\npm-debug.log

C:\prj\github-downloads\node-online-game-template>
```

**Comment by huytd** [comment]
Fixed with @keneo's PR
